In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 

import warnings 
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("data.csv")
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,2014-07-09 00:00:00,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [4]:
df.shape

(4600, 18)

In [5]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [6]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [7]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [8]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df[['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot','floors', 'waterfront', 'view', 'condition','sqft_basement', 'yr_built', 'yr_renovated','statezip']]

In [11]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_basement,yr_built,yr_renovated,statezip
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,0,1955,2005,WA 98133
1,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,280,1921,0,WA 98119
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,0,1966,0,WA 98042
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1963,0,WA 98008
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,800,1976,1992,WA 98052
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,0,1954,1979,WA 98133
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,0,1983,2009,WA 98007
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,0,2009,0,WA 98059
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1020,1974,0,WA 98178
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,0,1990,0,WA 98042

In [12]:
import datetime
#To find current year we use 
current_year = datetime.datetime.now().year

In [13]:
# 1. yr_built ko House_Age mein badal do 
# Formula: Current Year - Year Built
df['house_age'] = current_year - df['yr_built']

In [14]:
# 2. yr_renovated ko is_renovated (Binary) mein badalna
# Agar saal 0 se bada hai toh 1 (Yes), nahi toh 0 (No)
df['is_renovated'] = df['yr_renovated'].apply(lambda x: 1 if x > 0 else 0)

# 3. sqft_basement ko has_basement (Binary) mein badalna
# Agar basement area 0 se bada hai toh 1, nahi toh 0
df['has_basement'] = df['sqft_basement'].apply(lambda x: 1 if x > 0 else 0)

In [15]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_basement,yr_built,yr_renovated,statezip,house_age,is_renovated,has_basement
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,0,1955,2005,WA 98133,71,1,0
1,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,280,1921,0,WA 98119,105,0,1
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,0,1966,0,WA 98042,60,0,0
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,1000,1963,0,WA 98008,63,0,1
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,800,1976,1992,WA 98052,50,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,0,1954,1979,WA 98133,72,1,0
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,0,1983,2009,WA 98007,43,1,0
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,0,2009,0,WA 98059,17,0,0
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,1020,1974,0,WA 98178,52,0,1
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,0,1990,0,WA 98042,36,0,0

In [16]:
#now remove the which is getted transformed 
cols_drop = ['yr_built', 'yr_renovated', 'sqft_basement']
df = df.drop(columns=cols_drop)

In [17]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,statezip,house_age,is_renovated,has_basement
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,WA 98133,71,1,0
1,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,WA 98119,105,0,1
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,WA 98042,60,0,0
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,WA 98008,63,0,1
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,WA 98052,50,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,WA 98133,72,1,0
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,WA 98007,43,1,0
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,WA 98059,17,0,0
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,WA 98178,52,0,1
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,WA 98042,36,0,0

In [18]:
# now statezip has both alphabet and number lets fix thatabs

# 'WA 98133' se '98133' nikalne ke liye
df['zipcode'] = df['statezip'].apply(lambda x: x.split(' ')[1])

# Isse integer mein convert karein taaki model ise number samjhe
df['zipcode'] = df['zipcode'].astype(int)

# Purana column drop kardein
df = df.drop('statezip', axis=1)
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,house_age,is_renovated,has_basement,zipcode
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,0,3,71,1,0,98133
1,2.384000e+06,5.0,2.50,3650,9050,2.0,0,4,5,105,0,1,98119
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,0,4,60,0,0,98042
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,0,4,63,0,1,98008
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,0,4,50,1,1,98052
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,0,4,72,1,0,98133
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,0,3,43,1,0,98007
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,0,3,17,0,0,98059
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,0,3,52,0,1,98178
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,0,4,36,0,0,98042

In [19]:
#lets do standard scaling :-

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# In columns ko scale karna zaroori hai
scale_columns = ['sqft_living', 'sqft_lot', 'house_age', 'zipcode' , 'bedrooms' , "floors"]

df[scale_columns] = scaler.fit_transform(df[scale_columns])

In [21]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,house_age,is_renovated,has_basement,zipcode
0,3.130000e+05,-0.441122,1.50,-0.829971,-0.193434,-0.022416,0,0,3,0.531014,1,0,1.009107
1,2.384000e+06,1.759705,2.50,1.568528,-0.161718,0.906555,0,4,5,1.674693,0,1,0.745633
2,3.420000e+05,-0.441122,2.00,-0.217367,-0.080978,-0.951388,0,0,4,0.161000,0,0,-0.703469
3,4.200000e+05,-0.441122,2.25,-0.144686,-0.190145,-0.951388,0,0,4,0.261913,0,1,-1.343333
4,5.500000e+05,0.659291,2.50,-0.206984,-0.121306,-0.951388,0,0,4,-0.175376,1,1,-0.515274
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,-0.441122,1.75,-0.653458,-0.236689,-0.951388,0,0,4,0.564651,1,0,1.009107
4596,5.343333e+05,-0.441122,2.50,-0.705374,-0.202882,0.906555,0,0,3,-0.410840,1,0,-1.362153
4597,4.169042e+05,-0.441122,2.50,0.904009,-0.218462,0.906555,0,0,3,-1.285418,0,0,-0.383538
4598,2.034000e+05,0.659291,2.00,-0.051238,-0.229164,-0.951388,0,0,3,-0.108101,0,1,1.855985
4599,2.206000e+05,-0.441122,2.50,-0.674224,-0.188139,0.906555,0,0,4,-0.646303,0,0,-0.703469

In [22]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,house_age,is_renovated,has_basement,zipcode
0,313000.0,-0.441122,1.50,-0.829971,-0.193434,-0.022416,0,0,3,0.531014,1,0,1.009107
1,2384000.0,1.759705,2.50,1.568528,-0.161718,0.906555,0,4,5,1.674693,0,1,0.745633
2,342000.0,-0.441122,2.00,-0.217367,-0.080978,-0.951388,0,0,4,0.161000,0,0,-0.703469
3,420000.0,-0.441122,2.25,-0.144686,-0.190145,-0.951388,0,0,4,0.261913,0,1,-1.343333
4,550000.0,0.659291,2.50,-0.206984,-0.121306,-0.951388,0,0,4,-0.175376,1,1,-0.515274

In [23]:
# 1. Sabse pehle apna original cleaned dataframe (jisne transformations ho chuki hain) save rakhein
df_original = df.copy()

# --- TASK A: Logistic Regression (Classification) ---
df_clf = df_original.copy()
# Category banayein
df_clf['price_category'] = pd.qcut(df_clf['price'], q=3, labels=[0, 1, 2])
# Price hata dein kyunki yahan target category hai
df_clf.drop('price', axis=1, inplace=True)


# --- TASK B: Regression (KNN, Linear Regression) ---
df_reg = df_original.copy()
# Yahan price category ki zaroorat nahi hai, sirf asli price rahegi
# (Agar aapne df_original mein category nahi banayi thi, toh yahan kuch drop karne ki zaroorat nahi)

In [24]:
df_original

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,house_age,is_renovated,has_basement,zipcode
0,3.130000e+05,-0.441122,1.50,-0.829971,-0.193434,-0.022416,0,0,3,0.531014,1,0,1.009107
1,2.384000e+06,1.759705,2.50,1.568528,-0.161718,0.906555,0,4,5,1.674693,0,1,0.745633
2,3.420000e+05,-0.441122,2.00,-0.217367,-0.080978,-0.951388,0,0,4,0.161000,0,0,-0.703469
3,4.200000e+05,-0.441122,2.25,-0.144686,-0.190145,-0.951388,0,0,4,0.261913,0,1,-1.343333
4,5.500000e+05,0.659291,2.50,-0.206984,-0.121306,-0.951388,0,0,4,-0.175376,1,1,-0.515274
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,-0.441122,1.75,-0.653458,-0.236689,-0.951388,0,0,4,0.564651,1,0,1.009107
4596,5.343333e+05,-0.441122,2.50,-0.705374,-0.202882,0.906555,0,0,3,-0.410840,1,0,-1.362153
4597,4.169042e+05,-0.441122,2.50,0.904009,-0.218462,0.906555,0,0,3,-1.285418,0,0,-0.383538
4598,2.034000e+05,0.659291,2.00,-0.051238,-0.229164,-0.951388,0,0,3,-0.108101,0,1,1.855985
4599,2.206000e+05,-0.441122,2.50,-0.674224,-0.188139,0.906555,0,0,4,-0.646303,0,0,-0.703469

In [25]:
df_clf

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,house_age,is_renovated,has_basement,zipcode,price_category
0,-0.441122,1.50,-0.829971,-0.193434,-0.022416,0,0,3,0.531014,1,0,1.009107,0
1,1.759705,2.50,1.568528,-0.161718,0.906555,0,4,5,1.674693,0,1,0.745633,2
2,-0.441122,2.00,-0.217367,-0.080978,-0.951388,0,0,4,0.161000,0,0,-0.703469,0
3,-0.441122,2.25,-0.144686,-0.190145,-0.951388,0,0,4,0.261913,0,1,-1.343333,1
4,0.659291,2.50,-0.206984,-0.121306,-0.951388,0,0,4,-0.175376,1,1,-0.515274,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,-0.441122,1.75,-0.653458,-0.236689,-0.951388,0,0,4,0.564651,1,0,1.009107,0
4596,-0.441122,2.50,-0.705374,-0.202882,0.906555,0,0,3,-0.410840,1,0,-1.362153,1
4597,-0.441122,2.50,0.904009,-0.218462,0.906555,0,0,3,-1.285418,0,0,-0.383538,1
4598,0.659291,2.00,-0.051238,-0.229164,-0.951388,0,0,3,-0.108101,0,1,1.855985,0
4599,-0.441122,2.50,-0.674224,-0.188139,0.906555,0,0,4,-0.646303,0,0,-0.703469,0

In [26]:
# now lets use logestic regression :-

In [27]:
x= df_clf.drop("price_category" , axis =1)
y=df_clf['price_category']

In [28]:
from sklearn.model_selection import train_test_split 

x_train , x_test , y_train , y_test  = train_test_split(x,y,test_size=0.20 , random_state=42)

In [29]:
#use logestic regression :-
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression()

model.fit(x_train , y_train )

LogisticRegression()

In [30]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 2, 1, 1, 2, 1, 0, 1, 1, 2, 1, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2,
       1, 1, 0, 0, 2, 2, 0, 2, 2, 1, 2, 0, 0, 0, 2, 2, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 2, 2, 1, 2, 1, 1, 2, 0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1,
       2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 1, 2, 1, 0, 1, 0, 1, 2, 0, 0, 0, 1,
       2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 0, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2,
       2, 1, 0, 0, 2, 1, 1, 2, 1, 0, 2, 2, 2, 1, 0, 0, 2, 0, 0, 2, 0, 1,
       2, 0, 0, 0, 0, 0, 2, 2, 0, 1, 1, 1, 2, 2, 0, 0, 0, 1, 0, 2, 2, 1,
       2, 2, 2, 2, 1, 0, 1, 2, 0, 2, 1, 2, 2, 0, 2, 2, 0, 1, 2, 1, 2, 2,
       0, 2, 2, 0, 1, 0, 2, 0, 0, 2, 2, 0, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2,
       0, 0, 1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 0, 0, 1, 0,
       2, 2, 0, 1, 2, 1, 0, 0, 1, 2, 0, 0, 0, 1, 2, 2, 2, 1, 0, 0, 1, 1,
       0, 1, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 1, 1, 0, 1, 0, 0,
       1, 2, 2, 0, 0, 0, 2, 2, 0, 2, 1, 0, 0, 1, 2, 0, 1, 1, 1, 2, 1, 0,
       2, 1, 2, 1, 0, 1, 0, 2, 1, 1, 2, 2, 0, 1, 0, 2, 0, 2, 2, 2, 0, 0,
       1, 1, 2, 2, 2, 2, 1, 2, 0, 1, 2, 0, 2, 1, 1, 2, 0, 1, 0, 0, 2, 1,
       0, 2, 0, 1, 2, 0, 1, 2, 1, 2, 0, 0, 0, 1, 2, 0, 1, 2, 0, 0, 1, 0,
       2, 0, 1, 0, 0, 2, 0, 2, 1, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 2, 1, 0,
       1, 1, 0, 2, 1, 1, 1, 0, 0, 1, 0, 2, 0, 2, 1, 1, 0, 1, 0, 2, 0, 2,
       1, 2, 1, 1, 1, 1, 2, 2, 2, 0, 2, 2, 0, 1, 1, 2, 0, 1, 1, 1, 0, 2,
       0, 1, 1, 0, 1, 1, 2, 0, 2, 1, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 0, 2,
       2, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 1, 2, 0, 2, 2, 2, 0, 1,
       0, 2, 0, 2, 1, 2, 1, 2, 0, 2, 0, 0, 0, 1, 2, 2, 0, 1, 0, 2, 2, 2,
       0, 1, 2, 0, 0, 0, 2, 1, 2, 0, 0, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 2,
       1, 0, 1, 0, 0, 1, 2, 2, 2, 1, 1, 1, 1, 2, 0, 1, 0, 0, 1, 0, 2, 0,
       0, 0, 0, 1, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 0, 1, 1, 2, 0, 2, 1, 2,
       0, 0, 2, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 0, 1, 2, 1, 2, 1, 2, 0,
       2, 2, 0, 1, 2, 2, 2, 0, 0, 0, 1, 2, 1, 0, 1, 1, 2, 0, 0, 2, 0, 0,
       1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 1, 1, 0, 1, 2, 2, 2, 1, 0, 1, 2, 2, 1, 1, 0,
       1, 2, 2, 0, 1, 2, 0, 0, 1, 1, 2, 2, 0, 1, 0, 0, 2, 2, 0, 0, 2, 0,
       1, 1, 0, 2, 0, 2, 0, 0, 1, 0, 1, 2, 0, 2, 2, 1, 2, 2, 0, 1, 2, 1,
       0, 1, 1, 0, 1, 0, 0, 2, 2, 2, 1, 2, 2, 0, 1, 0, 0, 1, 2, 2, 0, 2,
       2, 2, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0,
       0, 1, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 2, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 2, 2, 2, 2, 0, 1, 1, 0, 2,
       0, 0, 1, 0, 2, 1, 0, 1, 2, 0, 0, 2, 2, 0, 1, 1, 0, 1, 2, 0, 1, 0,
       1, 1, 2, 0, 1, 2, 0, 0, 1, 1, 1, 1, 0, 2, 1, 2, 1, 2, 0, 0, 0, 0,
       2, 2, 1, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2,
       0, 0, 1, 2, 2, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0,
       2, 2, 0, 1, 2, 0, 2, 2, 0, 2, 1, 0, 1, 2, 1, 2, 2, 2, 0, 1, 2, 1,
       2, 2, 2, 2, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 1, 0, 2, 1, 0, 2, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 0, 2, 2])

In [31]:
y_test

3683    1
4411    0
2584    2
69      0
1844    0
       ..
1612    2
1068    0
4350    2
3027    2
3455    0
Name: price_category, Length: 920, dtype: category
Categories (3, int64): [0 < 1 < 2]

In [32]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [33]:
accuracy_score(y_test , y_pred)

0.5989130434782609

In [34]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.64      0.67      0.66       314
           1       0.46      0.44      0.45       298
           2       0.68      0.68      0.68       308

    accuracy                           0.60       920
   macro avg       0.59      0.60      0.60       920
weighted avg       0.60      0.60      0.60       920

In [35]:
confusion_matrix(y_test , y_pred)

array([[210,  78,  26],
       [ 93, 131,  74],
       [ 23,  75, 210]])

**NOW MAKE MODEL USING KNN**

In [36]:
df_original

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,house_age,is_renovated,has_basement,zipcode
0,3.130000e+05,-0.441122,1.50,-0.829971,-0.193434,-0.022416,0,0,3,0.531014,1,0,1.009107
1,2.384000e+06,1.759705,2.50,1.568528,-0.161718,0.906555,0,4,5,1.674693,0,1,0.745633
2,3.420000e+05,-0.441122,2.00,-0.217367,-0.080978,-0.951388,0,0,4,0.161000,0,0,-0.703469
3,4.200000e+05,-0.441122,2.25,-0.144686,-0.190145,-0.951388,0,0,4,0.261913,0,1,-1.343333
4,5.500000e+05,0.659291,2.50,-0.206984,-0.121306,-0.951388,0,0,4,-0.175376,1,1,-0.515274
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,-0.441122,1.75,-0.653458,-0.236689,-0.951388,0,0,4,0.564651,1,0,1.009107
4596,5.343333e+05,-0.441122,2.50,-0.705374,-0.202882,0.906555,0,0,3,-0.410840,1,0,-1.362153
4597,4.169042e+05,-0.441122,2.50,0.904009,-0.218462,0.906555,0,0,3,-1.285418,0,0,-0.383538
4598,2.034000e+05,0.659291,2.00,-0.051238,-0.229164,-0.951388,0,0,3,-0.108101,0,1,1.855985
4599,2.206000e+05,-0.441122,2.50,-0.674224,-0.188139,0.906555,0,0,4,-0.646303,0,0,-0.703469

In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
knn_model1 = KNeighborsClassifier(n_neighbors=5)
knn_model1.fit(x_train,y_train)

KNeighborsClassifier()

In [39]:
y_pred_knn = knn_model1.predict(x_test) 
y_pred_knn

array([1, 0, 2, 1, 1, 1, 1, 0, 0, 0, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, 0,
       2, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 0, 1, 2, 2, 2, 0, 1, 2, 0, 2, 2, 1,
       2, 2, 0, 0, 2, 0, 0, 2, 1, 2, 1, 2, 1, 0, 1, 1, 1, 2, 1, 0, 1, 2,
       2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1, 0, 0, 0, 2, 2, 0, 1, 1,
       2, 1, 0, 0, 2, 2, 2, 2, 1, 0, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 0, 0,
       2, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 2, 1, 1,
       2, 2, 2, 1, 1, 1, 1, 2, 0, 0, 1, 1, 2, 0, 0, 2, 1, 1, 2, 1, 2, 1,
       0, 2, 1, 0, 0, 0, 2, 0, 1, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 2, 1, 2,
       0, 0, 1, 2, 0, 2, 0, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 0, 1, 0, 1, 1,
       1, 2, 0, 1, 2, 1, 0, 1, 2, 2, 1, 0, 0, 1, 2, 2, 2, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 2, 0, 1, 2, 1, 2, 2, 2, 0, 1, 0, 0,
       1, 1, 2, 1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 1, 2, 0, 0, 0, 1, 2, 1, 0,
       2, 1, 2, 0, 1, 1, 0, 2, 0, 1, 2, 2, 0, 0, 0, 2, 1, 2, 1, 1, 0, 0,
       1, 1, 2, 2, 2, 2, 2, 1, 1, 0, 2, 0, 1, 1, 1, 2, 0, 1, 0, 0, 2, 1,
       0, 2, 2, 1, 2, 0, 2, 2, 0, 2, 0, 0, 0, 1, 2, 1, 1, 2, 0, 0, 1, 0,
       2, 1, 1, 0, 0, 1, 0, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 0, 1, 2, 1, 0,
       1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 1, 2,
       1, 2, 2, 1, 1, 1, 2, 1, 1, 0, 2, 1, 0, 2, 1, 2, 0, 2, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 2, 2, 2, 2, 1, 2, 0, 2, 1, 1, 2, 2, 2, 1, 2,
       0, 1, 0, 2, 1, 2, 1, 2, 1, 2, 1, 0, 0, 0, 2, 2, 0, 1, 0, 2, 2, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 2, 1, 0, 0, 2, 2, 2, 0, 1, 0, 1, 1, 1, 2,
       1, 0, 1, 0, 1, 2, 2, 2, 1, 1, 1, 0, 0, 2, 1, 2, 0, 0, 1, 0, 2, 0,
       1, 2, 0, 1, 0, 2, 0, 1, 1, 2, 0, 0, 1, 0, 0, 2, 0, 2, 1, 2, 1, 1,
       0, 0, 2, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1, 1, 0, 1, 2, 1, 2, 1, 2, 0,
       1, 1, 0, 1, 2, 2, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2,
       0, 0, 0, 2, 1, 2, 2, 0, 0, 0, 1, 2, 2, 2, 1, 0, 1, 1, 2, 1, 0, 0,
       0, 2, 2, 1, 0, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 1, 2, 2, 0, 0, 2, 0,
       1, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 2, 0, 2, 2, 1, 2, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 2, 1, 2, 1, 2, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2,
       2, 2, 0, 1, 0, 1, 2, 1, 2, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 0, 0,
       0, 1, 0, 0, 2, 2, 2, 2, 1, 2, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       2, 0, 0, 1, 2, 1, 1, 1, 0, 2, 0, 2, 1, 2, 1, 2, 2, 0, 1, 0, 0, 2,
       0, 1, 1, 1, 1, 1, 0, 0, 2, 2, 0, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 2, 1, 1, 0, 1, 0, 2, 1, 2, 0, 1, 1, 2, 1, 0, 0, 1,
       2, 2, 1, 0, 1, 1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 0, 2, 1, 1, 0, 1, 2,
       0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 1, 1, 1, 0, 2, 2, 2, 2, 0, 1,
       0, 2, 1, 1, 2, 0, 1, 1, 1, 2, 0, 1, 0, 1, 0, 2, 2, 2, 1, 1, 2, 1,
       2, 2, 1, 0, 0, 0, 1, 1, 1, 0, 2, 0, 1, 2, 0, 1, 0, 1, 1, 0, 2, 0,
       0, 1, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 1, 0, 0, 0, 2, 0])

In [40]:
accuracy_score(y_test , y_pred_knn)

0.5728260869565217

let's use navie bayes

In [41]:
from sklearn.naive_bayes import GaussianNB

In [42]:
model_nb = GaussianNB() 
model_nb.fit(x_train,y_train)

GaussianNB()

In [43]:
y_pred_nb = model_nb.predict(x_test)

In [44]:
y_pred_nb

array([1, 0, 2, 1, 0, 1, 0, 0, 0, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1,
       0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 2, 0, 2, 1, 0, 0, 0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 1, 1,
       1, 1, 1, 0, 2, 0, 0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1,
       2, 0, 2, 0, 0, 0, 2, 2, 2, 1, 0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 1, 1,
       0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 2, 1, 0, 1, 0, 0, 0, 2, 1, 0,
       2, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 1, 1, 2, 2,
       0, 2, 2, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0, 0, 2, 1, 2, 1, 2,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       2, 2, 0, 0, 2, 1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 2, 2, 1, 0, 0, 0, 0,
       0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 2, 1, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 2, 1, 2, 1, 0, 0, 0,
       0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0,
       2, 0, 1, 0, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 2, 0, 0,
       1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 2, 0, 2,
       0, 1, 1, 1, 0, 0, 2, 2, 1, 0, 2, 0, 0, 0, 0, 2, 0, 2, 1, 1, 0, 2,
       0, 0, 0, 0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 1, 1, 0, 0, 1, 0, 1, 2, 2, 0, 2,
       0, 1, 0, 2, 0, 2, 0, 2, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 2, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2,
       0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 0, 2,
       0, 0, 2, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 2, 2, 2, 0, 1, 0,
       1, 0, 0, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0,
       1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 2, 0, 1, 1, 1,
       0, 1, 0, 2, 0, 1, 2, 0, 0, 0, 0, 2, 2, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 2, 2, 0, 0, 2, 0, 0, 1, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 2, 1, 0, 2, 2, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 2, 2, 0, 2,
       2, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 2, 2, 0, 0,
       0, 0, 0, 0, 1, 2, 2, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 2, 1, 0, 1, 0, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 1, 1, 0, 0, 2, 0, 2, 0,
       1, 2, 1, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2,
       0, 0, 1, 2, 2, 0, 0, 0, 0, 1, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 2, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2, 0, 0, 2, 0,
       2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0])

In [45]:
accuracy_score(y_test , y_pred)

0.5989130434782609

**USING DECISION TREE**

In [46]:
from sklearn.tree import DecisionTreeClassifier 
model_dt = DecisionTreeClassifier(random_state= 42)
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(random_state=42)

In [47]:
y_pred_dt = model_dt.predict(x_test)

In [48]:
accuracy_score(y_test , y_pred)

0.5989130434782609

**use svc**

In [49]:
from sklearn.svm import SVC 
model_svm = SVC(kernel='rbf') 
model_svm.fit(x_train,y_train)

SVC()

In [50]:
y_pred_svm = model_svm.predict(x_test)
accuracy_score(y_test , y_pred_svm)

0.5956521739130435

In [51]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Model Initialize karein
# n_estimators=100 ka matlab hai ye 100 alag-alag trees banayega
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

# 2. Model ko train karein
# Aap yahan X_train (bina scaling wala) bhi use kar sakte hain
rf_clf.fit(x_train, y_train)

# 3. Predictions
y_pred_rf = rf_clf.predict(x_test)

# 4. Accuracy Check
print(f"Random Forest Accuracy: {accuracy_score(y_test, y_pred_rf) * 100:.2f}%")
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

Random Forest Accuracy: 65.87%

Confusion Matrix:
 [[221  73  20]
 [ 64 161  73]
 [ 16  68 224]]

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         4600 non-null   float64
 1   bedrooms      4600 non-null   float64
 2   bathrooms     4600 non-null   float64
 3   sqft_living   4600 non-null   float64
 4   sqft_lot      4600 non-null   float64
 5   floors        4600 non-null   float64
 6   waterfront    4600 non-null   int64
 7   view          4600 non-null   int64
 8   condition     4600 non-null   int64
 9   house_age     4600 non-null   float64
 10  is_renovated  4600 non-null   int64
 11  has_basement  4600 non-null   int64
 12  zipcode       4600 non-null   float64
dtypes: float64(8), int64(5)
memory usage: 467.3 KB

In [53]:
df_clf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bedrooms        4600 non-null   float64
 1   bathrooms       4600 non-null   float64
 2   sqft_living     4600 non-null   float64
 3   sqft_lot        4600 non-null   float64
 4   floors          4600 non-null   float64
 5   waterfront      4600 non-null   int64
 6   view            4600 non-null   int64
 7   condition       4600 non-null   int64
 8   house_age       4600 non-null   float64
 9   is_renovated    4600 non-null   int64
 10  has_basement    4600 non-null   int64
 11  zipcode         4600 non-null   float64
 12  price_category  4600 non-null   category
dtypes: category(1), float64(7), int64(5)
memory usage: 436.0 KB

In [54]:
print(df_clf.dtypes)

bedrooms           float64
bathrooms          float64
sqft_living        float64
sqft_lot           float64
floors             float64
waterfront           int64
view                 int64
condition            int64
house_age          float64
is_renovated         int64
has_basement         int64
zipcode            float64
price_category    category
dtype: object

In [55]:
from sklearn.linear_model import LinearRegression

In [56]:
reg = LinearRegression().fit(x, y)

In [57]:
reg

LinearRegression()

In [59]:
reg.score(x, y)

0.3556602873171514